import pyautogui
import time

time.sleep(10)
count=2

for i in range (15):
    count = count+1
    time.sleep(0.2)
    pyautogui.keyDown('alt')
    time.sleep(0.2)
    pyautogui.keyDown('tab')
    time.sleep(0.2)
    pyautogui.keyUp('tab')
    time.sleep(0.2)
    pyautogui.keyUp('alt')
    time.sleep(5)
    pyautogui.press('enter')
    time.sleep(0.5)
    pyautogui.write('clear')
    time.sleep(0.2)
    pyautogui.press('enter')
    time.sleep(1.5)
    pyautogui.write('./run-contest LucasZick')
    time.sleep(0.2)
    pyautogui.press('enter')
    time.sleep(180)
    #baixo(x=76, y=224)
    #cima(x=86, y=133)
    pyautogui.moveTo(x=76,y=224)
    pyautogui.mouseDown(button='left')
    pyautogui.dragTo(x=86,y=133,duration=2)
    pyautogui.mouseUp(button='left')
    pyautogui.click(button='right')
    time.sleep(0.2)
    pyautogui.press('down')
    time.sleep(0.2)
    pyautogui.press('enter')
    time.sleep(0.2)
    pyautogui.keyDown('alt')
    time.sleep(0.2)
    pyautogui.press('tab')
    time.sleep(0.2)
    pyautogui.keyUp('alt')
    time.sleep(1.5)
    pyautogui.write('RESULTADO '+ str(count))
    for k in range(2):
        time.sleep(0.2)
        pyautogui.press('enter')
        time.sleep(0.2)
    pyautogui.keyDown('ctrl')
    time.sleep(0.2)
    pyautogui.press('v')
    time.sleep(0.2)
    pyautogui.keyUp('ctrl')
    for j in range(3):
        time.sleep(0.2)
        pyautogui.press('enter')
        time.sleep(0.2)
    time.sleep(1.5)
    pyautogui.keyDown('ctrl')
    time.sleep(0.2)
    pyautogui.press('s')
    time.sleep(0.2)
    pyautogui.keyUp('ctrl')

print('FINALIZADO')
